### PR TITLE
Adapting SCCM custom role to match AL5

### PR DESCRIPTION
**Pull request by raandree**

### CODE REVIEW

**Comment by raandree** [comment]
Hi Glenn,

I have added the custom role to AL. Can you move your work to a fork of AL? This would give your work more visibility and integrates it right into AL. If you want to stay here, I will try to migrate your work into the AL project.

How difficult is it to put some life into the SCCM deployment. It would be nice to have operating systems there and some software to install like with the MDT role.

Thanks for the great work! I will mention this at the http://www.psconf.eu/ next week.

**Comment by raandree** [comment]
Did you have seen this? http://automatedlab.org/. It shown also how often your roles are used!

**Comment by GlennJC** [comment]
> I have added the custom role to AL. Can you move your work to a fork of AL? This would give your work more visibility and integrates it right into AL. If you want to stay here, I will try to migrate your work into the AL project.

Sure, no worries, should be easy to do. I'll have to get the hang of pull requests :)

> How difficult is it to put some life into the SCCM deployment. It would be nice to have operating systems there and some software to install like with the MDT role.

I have an version of the script that I have started doing this exact thing to, so will start cleaning it up. One thing I have been thinking about is continued use of functions (for example Add-SCCMOperatingSystem) once the main script has run. I'm leaning towards having to make this a module, any suggestions on a workable alternative?

> Thanks for the great work! I will mention this at the http://www.psconf.eu/ next week.

No worries at all! Thanks for all the help (and a great framework to work with) :)

> Did you have seen this? http://automatedlab.org/. It shown also how often your roles are used!

I haven't ! That's great !

**Comment by raandree** [comment]
Using forks and pull requests makes the collaboration quite easy. If you are fine with the changes, you can merge #12. I have added / changed the same code in AL.

The functionality that is not directly linked to AutomatedLab is in [AutomatedLab.Common](https://github.com/AutomatedLab/AutomatedLab.Common). We are thinking to rename the module so it has no link to AutomatedLab at all. This could be a good place for your SCCM functions.

Can you give me your twitter handle if you have one. I would like to mention you when announcing the new SCCM role.

**Comment by GlennJC** [comment]
Looks good, merged in.

Thanks for that, I'll look into a good way to integrate additional functions for the various roles, always thinking of new features to add :)

twitter handle is @GJCorb. Has just been set up, my old handle got hacked. Thanks for the mention :) Good luck at the conference !

**Pull request merged**
